# Generated by Django 3.2.8 on 2021-10-10 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_sppr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.CharField(max_length=100, null=True, verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='book',
            name='name',
            field=models.CharField(max_length=100, null=True, verbose_name='date created'),
        ),
    ]
